# Generated by Django 3.2.6 on 2021-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mikrot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mikrotIP', models.CharField(max_length=20, verbose_name='Адрес Микротик')),
                ('mikrotName', models.CharField(max_length=20, verbose_name='Имя Микротик')),
                ('mikrotPass', models.CharField(max_length=20, verbose_name='Пароль Микротик')),
            ],
        ),
    ]
