# Generated by Django 3.2.6 on 2021-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrot',
            name='mikrotName',
            field=models.CharField(max_length=30, verbose_name='Имя Микротик'),
        ),
    ]
