# Generated by Django 3.2.6 on 2021-09-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_mikrot_mikrotname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mikrot',
            options={'permissions': (('index', 'User not auth'),), 'verbose_name': 'Микротик', 'verbose_name_plural': 'Микротики'},
        ),
    ]
