# Generated by Django 3.2.6 on 2021-09-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_mikrot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mikrot',
            options={'permissions': (('detail', 'User not auth'),), 'verbose_name': 'Микротик', 'verbose_name_plural': 'Микротики'},
        ),
    ]
