# Generated by Django 3.2.6 on 2021-09-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_mikrot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mikrot',
            options={'verbose_name': 'Микротик', 'verbose_name_plural': 'Микротики'},
        ),
    ]
