# Generated by Django 3.2.7 on 2021-09-14 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_mikrot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrot',
            name='mikrotLogin',
            field=models.CharField(default=datetime.datetime(2021, 9, 14, 7, 7, 22, 210915, tzinfo=utc), max_length=30, verbose_name='Логин Микротик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mikrot',
            name='mikrotPass',
            field=models.CharField(max_length=30, verbose_name='Пароль Микротик'),
        ),
    ]
